// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package application

import (
	"github.com/diwise/api-environment/internal/pkg/infrastructure/repositories/models"
	"sync"
	"time"
)

// Ensure, that EnvironmentAppMock does implement EnvironmentApp.
// If this is not the case, regenerate this file with moq.
var _ EnvironmentApp = &EnvironmentAppMock{}

// EnvironmentAppMock is a mock implementation of EnvironmentApp.
//
// 	func TestSomethingThatUsesEnvironmentApp(t *testing.T) {
//
// 		// make and configure a mocked EnvironmentApp
// 		mockedEnvironmentApp := &EnvironmentAppMock{
// 			RetrieveAirQualityObservedsFunc: func(deviceId string, from time.Time, to time.Time, limit uint64) ([]models.AirQualityObserved, error) {
// 				panic("mock out the RetrieveAirQualityObserveds method")
// 			},
// 			StoreAirQualityObservedFunc: func(entityId string, deviceId string, co2 float64, humidity float64, temperature float64, timestamp time.Time) error {
// 				panic("mock out the StoreAirQualityObserved method")
// 			},
// 		}
//
// 		// use mockedEnvironmentApp in code that requires EnvironmentApp
// 		// and then make assertions.
//
// 	}
type EnvironmentAppMock struct {
	// RetrieveAirQualityObservedsFunc mocks the RetrieveAirQualityObserveds method.
	RetrieveAirQualityObservedsFunc func(deviceId string, from time.Time, to time.Time, limit uint64) ([]models.AirQualityObserved, error)

	// StoreAirQualityObservedFunc mocks the StoreAirQualityObserved method.
	StoreAirQualityObservedFunc func(entityId string, deviceId string, co2 float64, humidity float64, temperature float64, timestamp time.Time) error

	// calls tracks calls to the methods.
	calls struct {
		// RetrieveAirQualityObserveds holds details about calls to the RetrieveAirQualityObserveds method.
		RetrieveAirQualityObserveds []struct {
			// DeviceId is the deviceId argument value.
			DeviceId string
			// From is the from argument value.
			From time.Time
			// To is the to argument value.
			To time.Time
			// Limit is the limit argument value.
			Limit uint64
		}
		// StoreAirQualityObserved holds details about calls to the StoreAirQualityObserved method.
		StoreAirQualityObserved []struct {
			// EntityId is the entityId argument value.
			EntityId string
			// DeviceId is the deviceId argument value.
			DeviceId string
			// Co2 is the co2 argument value.
			Co2 float64
			// Humidity is the humidity argument value.
			Humidity float64
			// Temperature is the temperature argument value.
			Temperature float64
			// Timestamp is the timestamp argument value.
			Timestamp time.Time
		}
	}
	lockRetrieveAirQualityObserveds sync.RWMutex
	lockStoreAirQualityObserved     sync.RWMutex
}

// RetrieveAirQualityObserveds calls RetrieveAirQualityObservedsFunc.
func (mock *EnvironmentAppMock) RetrieveAirQualityObserveds(deviceId string, from time.Time, to time.Time, limit uint64) ([]models.AirQualityObserved, error) {
	if mock.RetrieveAirQualityObservedsFunc == nil {
		panic("EnvironmentAppMock.RetrieveAirQualityObservedsFunc: method is nil but EnvironmentApp.RetrieveAirQualityObserveds was just called")
	}
	callInfo := struct {
		DeviceId string
		From     time.Time
		To       time.Time
		Limit    uint64
	}{
		DeviceId: deviceId,
		From:     from,
		To:       to,
		Limit:    limit,
	}
	mock.lockRetrieveAirQualityObserveds.Lock()
	mock.calls.RetrieveAirQualityObserveds = append(mock.calls.RetrieveAirQualityObserveds, callInfo)
	mock.lockRetrieveAirQualityObserveds.Unlock()
	return mock.RetrieveAirQualityObservedsFunc(deviceId, from, to, limit)
}

// RetrieveAirQualityObservedsCalls gets all the calls that were made to RetrieveAirQualityObserveds.
// Check the length with:
//     len(mockedEnvironmentApp.RetrieveAirQualityObservedsCalls())
func (mock *EnvironmentAppMock) RetrieveAirQualityObservedsCalls() []struct {
	DeviceId string
	From     time.Time
	To       time.Time
	Limit    uint64
} {
	var calls []struct {
		DeviceId string
		From     time.Time
		To       time.Time
		Limit    uint64
	}
	mock.lockRetrieveAirQualityObserveds.RLock()
	calls = mock.calls.RetrieveAirQualityObserveds
	mock.lockRetrieveAirQualityObserveds.RUnlock()
	return calls
}

// StoreAirQualityObserved calls StoreAirQualityObservedFunc.
func (mock *EnvironmentAppMock) StoreAirQualityObserved(entityId string, deviceId string, co2 float64, humidity float64, temperature float64, timestamp time.Time) error {
	if mock.StoreAirQualityObservedFunc == nil {
		panic("EnvironmentAppMock.StoreAirQualityObservedFunc: method is nil but EnvironmentApp.StoreAirQualityObserved was just called")
	}
	callInfo := struct {
		EntityId    string
		DeviceId    string
		Co2         float64
		Humidity    float64
		Temperature float64
		Timestamp   time.Time
	}{
		EntityId:    entityId,
		DeviceId:    deviceId,
		Co2:         co2,
		Humidity:    humidity,
		Temperature: temperature,
		Timestamp:   timestamp,
	}
	mock.lockStoreAirQualityObserved.Lock()
	mock.calls.StoreAirQualityObserved = append(mock.calls.StoreAirQualityObserved, callInfo)
	mock.lockStoreAirQualityObserved.Unlock()
	return mock.StoreAirQualityObservedFunc(entityId, deviceId, co2, humidity, temperature, timestamp)
}

// StoreAirQualityObservedCalls gets all the calls that were made to StoreAirQualityObserved.
// Check the length with:
//     len(mockedEnvironmentApp.StoreAirQualityObservedCalls())
func (mock *EnvironmentAppMock) StoreAirQualityObservedCalls() []struct {
	EntityId    string
	DeviceId    string
	Co2         float64
	Humidity    float64
	Temperature float64
	Timestamp   time.Time
} {
	var calls []struct {
		EntityId    string
		DeviceId    string
		Co2         float64
		Humidity    float64
		Temperature float64
		Timestamp   time.Time
	}
	mock.lockStoreAirQualityObserved.RLock()
	calls = mock.calls.StoreAirQualityObserved
	mock.lockStoreAirQualityObserved.RUnlock()
	return calls
}
